import type { LineupResponse } from "@/types/timeline";

export const demoLineup: LineupResponse = {
  timeline: {
    id: "demo-550e8400-e29b-41d4-a716-446655440099",
    title: "Asaya — Luxury 20s Instagram Ad",
    brandWorkspaceId: "550e8400-e29b-41d4-a716-446655440001",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    totalDuration: 20,
    aspectRatio: "9:16",
    targetPlatform: "instagram",
    isLocked: false,
    globalColorGrade: "Asaya Luxury",
    scenes: [
      {
        id: "scene-001",
        order: 0,
        label: "Opening — Brand Reveal",
        description: "Slow cinematic reveal of a luxury product on a dark velvet surface. Camera pulls back gradually.",
        duration: 4,
        transition: { type: "cinematic-fade", duration: 0.8 },
        captions: [
          { id: "cap-001", text: "WHERE LUXURY BEGINS", startTime: 1.2, endTime: 3.5, style: "brand-default" },
        ],
        overlays: [],
        motionStyle: "slow-pan",
        mood: "luxury",
      },
      {
        id: "scene-002",
        order: 1,
        label: "Product Detail — Close Up",
        description: "Extreme close-up of product texture and craftsmanship. Warm light raking across surfaces.",
        duration: 4,
        transition: { type: "dissolve", duration: 0.6 },
        captions: [
          { id: "cap-002", text: "CRAFTED FOR THE DISCERNING", startTime: 0.5, endTime: 3.2, style: "subtle" },
        ],
        overlays: [],
        motionStyle: "ken-burns",
        mood: "luxury",
      },
      {
        id: "scene-003",
        order: 2,
        label: "Lifestyle — Aspirational",
        description: "Model in elegant setting, soft backlight, slow movement. Conveys aspirational lifestyle.",
        duration: 5,
        transition: { type: "fade", duration: 0.7 },
        captions: [
          { id: "cap-003", text: "A WORLD APART", startTime: 0.8, endTime: 2.5, style: "highlight" },
          { id: "cap-004", text: "EXCLUSIVELY ASAYA", startTime: 3.0, endTime: 4.8, style: "brand-default" },
        ],
        overlays: [],
        motionStyle: "slow-pan",
        mood: "calm",
      },
      {
        id: "scene-004",
        order: 3,
        label: "Collection Wide Shot",
        description: "Full collection laid out artfully. Camera glides across items in a sweeping motion.",
        duration: 4,
        transition: { type: "cinematic-fade", duration: 1.0 },
        captions: [
          { id: "cap-005", text: "THE NEW COLLECTION", startTime: 0.6, endTime: 3.4, style: "bold" },
        ],
        overlays: [],
        motionStyle: "zoom-pulse",
        mood: "dramatic",
      },
      {
        id: "scene-005",
        order: 4,
        label: "Logo End Card",
        description: "Clean dark background, logo fades in centre. Tagline appears beneath. Holds for 3 seconds.",
        duration: 3,
        transition: { type: "fade", duration: 0.5 },
        captions: [
          { id: "cap-006", text: "ASAYA", startTime: 0.8, endTime: 2.8, style: "brand-default" },
        ],
        overlays: [
          {
            id: "overlay-logo",
            type: "logo",
            placement: { x: 37.5, y: 70, width: 25, alignment: "center" },
            startTime: 0.5,
            endTime: 3,
            opacity: 1,
            scale: 1,
          },
        ],
        motionStyle: "static",
        mood: "luxury",
      },
    ],
    audioLayers: [
      {
        id: "audio-bgm-001",
        type: "bgm",
        startTime: 0,
        endTime: 20,
        volume: 0.65,
        fadeIn: 1.2,
        fadeOut: 2.5,
      },
    ],
    meta: {
      generatedBy: "gemini-2.0-flash",
      promptUsed: "Create a 20-second premium Instagram ad for Asaya with cinematic transitions and luxury feel",
      brandWorkspaceId: "550e8400-e29b-41d4-a716-446655440001",
      qaScore: 94,
      qaNotes: "Strong brand alignment. Transitions match luxury tone. Captions within character limits. Logo correctly placed on final scene only.",
      version: 1,
    },
  },
  suggestions: {
    captionTiming: "Captions enter at 0.5–1.2s into each scene to allow visual establishment before text appears, and exit 0.5s before the scene ends for a clean feel.",
    transitionRationale: "Cinematic fades and dissolves used throughout — consistent with Asaya's luxury positioning. Hard cuts are avoided entirely.",
    brandNotes: "All captions use uppercase with wide letter-spacing, matching Cormorant Garamond brand font rules. Logo appears only on the final scene as specified in brand config.",
    improvements: [
      "Consider adding a subtle sound design SFX layer (e.g. gentle chime on logo reveal) for premium feel",
      "Scene 3 could use a secondary caption with a CTA such as 'SHOP NOW' in the last 1.5s",
      "A 0.5s color grade ramp at the start of Scene 1 would enhance the cinematic opening",
    ],
  },
};
